- SetupDataPkg/ConfApp/SecureBoot.c
- SetupDataPkg/ConfApp/UnitTest/ConfAppSecureBootUnitTest.c
The original code incorrectly set the state machine to "enroll" when selecting the "None" option. This change fixed the issue and added a corresponding unit test case.
> Fixed an issue of clearing Secure Boot enrollment

- SetupDataPkg/Tools/GenCfgData.py
This issue was introduced during cleaning the Python script for linting compliance. The original code will take the key from previous round of parsing, which will trip on the linting error. This change will set it to the global variable of this class instance to avoid linting violation or functional discontinuities.
> Fixed a Python tool issue introduced during cleaning

- SetupDataPkg/ConfApp/SystemInfo.c
The intention of the original code was to print a hint message when there is no FMP instance installed. But the current handling has the logic inverted. This change tries to fix it.
> Fixing a logic error when no FMP instance is installed

- SetupDataPkg/Tools/SettingSupport/DFCI_SupportLib.py
The ConfApp produces an SVD with <Settings><SettingCurrent>...</SettingCurrent></Settings> not <SettingsCurrent><SettingCurrent></SettingCurrent></Settings>.
> Fix incorrect naming for SVD coming from ConfApp

- .pytool/CISettings.py
- BasicDevTests.py
- SetupDataPkg/Tools/GenNCCfgData.py
- SetupDataPkg/Tools/SettingSupport/CertSupportLib.py
- SetupDataPkg/Tools/SettingSupport/DFCI_SupportLib.py
- SetupDataPkg/Tools/SettingSupport/Data/CertProvisioningVariable.py
- SetupDataPkg/Tools/SettingSupport/Data/PermissionPacketVariable.py
- SetupDataPkg/Tools/SettingSupport/Data/SecureSettingVariable.py
- SetupDataPkg/Tools/SettingSupport/UefiVariablesSupportLib.py
- SetupDataPkg/Tools/SettingSupport/UtilityFunctions.py
- py-requirements.txt
Flake8 just updated to 5.0.0 recently and start to catch new error that was not found. This is a designated PR to fix format errors on existing python files. No functional changes.
This change also starts to require flake8 to be at least v5.0.0 or later to perform pipeline checks.
> Fixing the python formats

- SetupDataPkg/ConfDataSettingProvider/ConfDataSettingProvider.c
Current setting providers for YAML configurations will print a list of errors as the result of get settings is not returning EFI_BUFFER_TOO_SMALL when the input buffer size is 0. This change will mitigate the errors by accepting this condition and populate the buffer size properly.
> Updated the checking condition for input arguments

- SetupDataPkg/ConfApp/ConfApp.inf
- SetupDataPkg/ConfApp/UnitTest/ConfAppBootOptionUnitTest.inf
- SetupDataPkg/ConfApp/UnitTest/ConfAppSecureBootUnitTest.inf
- SetupDataPkg/ConfApp/UnitTest/ConfAppSetupConfUnitTest.inf
- SetupDataPkg/ConfApp/UnitTest/ConfAppSysInfoUnitTest.inf
- SetupDataPkg/ConfApp/UnitTest/ConfAppUnitTest.inf
- SetupDataPkg/ConfDataSettingProvider/ConfDataSettingProvider.c
- SetupDataPkg/ConfDataSettingProvider/ConfDataSettingProvider.inf
- SetupDataPkg/ConfDataSettingProvider/UnitTest/ConfDataSettingProviderUnitTest.c
- SetupDataPkg/ConfDataSettingProvider/UnitTest/ConfDataSettingProviderUnitTest.inf
- SetupDataPkg/Docs/Overview/Overview.md
- SetupDataPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
- SetupDataPkg/SetupDataPkg.dec
As an effort of conforming XML and YAML configurations, a predefined GUID is more feasible for the peripheral tools to streamline the binary generations and upper layer consumptions.
This change replaces "PcdConfigPolicyVariableGuid" with "gSetupConfigPolicyVariableGuid".
> Removed the platform supplied GUID with hardcoded GUID

- SetupDataPkg/ConfApp/SetupConf.c
The original implementation would rely on the printing stack to print the entire collected xml as string, which is truncated by the %a parser. This change fixed the issue by dumping the string in a loop till all characters are printed.
> Fixing a truncated string output when trying to dump the current settings

- SetupDataPkg/ConfDfciUnsignedListInit/ConfDfciUnsignedListInit.c
- SetupDataPkg/ConfDfciUnsignedListInit/ConfDfciUnsignedListInit.inf
- SetupDataPkg/SetupDataPkg.dsc
- mu_plus_ext_dep.yaml
This change will change the DFCI unsigned setting's XML file GUID based on the current system mode. Such that on non-MFG mode, the DFCI will not accept unsigned settings. When the system is in MFG mode, the system will only block the settings listed in the XML file.
> Supply unsigned xml based on system operation mode

- SetupDataPkg/Plugins/GenSetupDataBin/GenSetupDataBin.py
Pass semicolon delimited arg in quotes to fix GCC consumption
> Fix Semicolon Delimiter for GCC

- SetupDataPkg/ConfDataSettingProvider/ConfDataSettingProvider.c
- SetupDataPkg/ConfDataSettingProvider/ConfDataSettingProvider.inf
- SetupDataPkg/ConfDataSettingProvider/UnitTest/ConfDataSettingProviderUnitTest.c
- SetupDataPkg/ConfDataSettingProvider/UnitTest/ConfDataSettingProviderUnitTest.inf
This change adds a check for system manufacturing mode and will not register for variable policies if so. This is to comply with the design of "profile and operation mode" contract.
> Added manufacturing mode check to not lock variables

- SetupDataPkg/ConfApp/SetupConf.c
The SVD data packet from USB is NULL terminated, which will cause a hang for the XML parser. This change fixed it by trimming the terminator before handing off to the XML parser.
This change is verified on QEMU Q35 virtual platform.
> Fixed applying SVD files from USB

- SetupDataPkg/ConfApp/ConfApp.inf
- SetupDataPkg/ConfApp/SystemInfo.c
- SetupDataPkg/ConfApp/UnitTest/ConfAppSysInfoUnitTest.inf
- SetupDataPkg/ConfDataSettingProvider/ConfDataSettingProvider.c
- SetupDataPkg/ConfDataSettingProvider/ConfDataSettingProvider.inf
- SetupDataPkg/ConfDataSettingProvider/UnitTest/ConfDataSettingProviderUnitTest.c
- SetupDataPkg/ConfDataSettingProvider/UnitTest/ConfDataSettingProviderUnitTest.inf
- SetupDataPkg/Library/ConfigBlobBaseLib/ConfigBlobBaseLib.inf
- SetupDataPkg/SetupDataPkg.ci.yaml
This change removed certain unnecessary dependencies from SetupDataPkg (including FmpPkg, PolicyServicesPkg) to make the package more platform agnostic.
Additionally, this change reverted the check of MFG mode in the settings provider driver. The expectation is that platforms will disable variable policy during MFG mode and variable policy will essentially be no-op.
> Remove unnecessary dependencies

- SetupDataPkg/Tools/ConfigEditor.py
- SetupDataPkg/Tools/GenNCCfgData.py
Load full variable list produced by dmpstore and ignore all variables that are not part of config.
> Support ConfigEditor Loading Full DmpStore Blob

- SetupDataPkg/Tools/GenCfgData.py
- SetupDataPkg/Tools/GenCfgData_test.py
- SetupDataPkg/Tools/samplecfg.yaml
- SetupDataPkg/Tools/samplecfg_UI.yaml
The original code had heuristic method to merge contiguous fields in a struct into an array of field. (i.e. GPIO_0, GPIO_1 -> GPIO[2]). However, when it comes to an array of structures, the `struct_dict` will be constructed to prevent duplicate structure definitions, `struct_list` will then be inherited from such dictionary with the heuristic method applied to the corresponding 'count' field.
During `create_struct` routine, the struct alias will be evaluated. This name could support a `[N]` notation, denoting there are N structures here. However, the output field will then be written using the 'count' value. This method is also less undesirable when it comes to specifying individual structure default values.
Thus, defining 2 fields with the same struct name, will be nullified by the …
> Fixing an error for the python script processing struct array

- SetupDataPkg/Plugins/GenSetupDataBin/GenSetupDataBin.py
Allow platform to specify empty string for delta file list.
> Allow Build Plugin to Accept Empty String

- SetupDataPkg/Tools/GenCfgData.py
The practical use case start to exceed the size limit defined by the 10bit length in the tag structure header.
This change extends the size limit to 18bit wide, which will allow up to 256K. The change will not impact the output binary/svd data as it is consumed internally by the GenCfgData.py script.
> Extended the size limit in the tag header to 18 bits

- basecore_ext_dep.yaml
- mu_plus_ext_dep.yaml
- mu_tiano_ext_dep.yaml
- pip-requirements.txt
Updated BASECORE, MU_PLUS and MU_TIANO_PLUS repos to be based on MU 202208 release branches.
> Update MU dependencies to be based on MU 202208

- SetupDataPkg/ConfApp/SystemInfo.c
- SetupDataPkg/ConfProfileMgrDxe/ConfProfileMgrDxe.c
Fixes the following issues reported by the DebugMacroCheck plugin:
```
Checking DEBUG Macros
File: ConfApp/SystemInfo.c
Message         = "%a - FMP ImageIdName is null\n"
Arguments       = ""
Specifier Count = 1
Argument Count  = 0
File: ConfApp/SystemInfo.c
Message         = "%a - FMP VersionName is null\n"
Arguments       = ""
Specifier Count = 1
Argument Count  = 0
File: ConfProfileMgrDxe/ConfProfileMgrDxe.c
Message         = "%a Failed to retrieve cached profile, using generic profile\n"
Arguments       = ", __FUNCTION__, Status"
Specifier Count = 1
Argument Count  = 2
3 debug macro errors in 34 files
Plugin Failed: Debug Macro Check Plugin returned 3
```
Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>
> SetupDataPkg: Fix imbalanced DEBUG macros

- SetupDataPkg/ConfApp/SetupConf.c
Fixed potentially uninitialized EncodedBuffer in CreateXmlStringFromCurrentSettings which causes the clang compiler to fail.
> Initialize potentially uninitialized variable in SetupConf

- SetupDataPkg/Tools/ConfigEditor.py
- SetupDataPkg/Tools/GenCfgData_test.py
- SetupDataPkg/Tools/GenNCCfgData.py
- SetupDataPkg/Tools/GenNCCfgData_test.py
Add support to the ConfigEditor UI tool to load multiple XML files, save them to combined binaries, load from single or multiple binaries, csv files, and SVD files.
> Support Loading Multiple XML Files

- SetupDataPkg/Tools/GenNCCfgData.py
- SetupDataPkg/Tools/VariableList.py
There is a current bug where saving a delta CSV saves the full config data to the CSV. This PR also makes a choice to not save all subknobs to the CSV in order to save space.
> Save Delta CSV When User Requests

- SetupDataPkg/Tools/VariableList.py
- SetupDataPkg/Tools/VariableList_test.py
During subknob updates the value could be incorrect resulting in a validation error and exception when updating the knob.
> Fixed issue where subknobs are updated

- SetupDataPkg/Tools/configschema.xsd
The schema defined in SetupDataPkg/Tools/configschema.xsd currently
enforces that a configuration definition must have enums and structs
defined. However, there are valid use-cases where a user may just want
to define knobs using standard data types. To support such use-cases
update the schema to make structs/enums optional.
> Make enums and structs optional in the xml schema

- SetupDataPkg/Tools/VariableList.py
Added a binary column to the CSV file format to show the binary representation of values.
This is added to aid users who need to manually update knobs by directly editing UEFI variables. The binary value shows the correct representation for a given value.
The value is written by the tools, but is ignored when read, similar to the Comment/Help column. The Help column was renamed to Comment to make clear it can be used for other notes in saved CSVs. 
Manually verified
> Added binary CSV column

- SetupDataPkg/ConfApp/SetupConf.c
- SetupDataPkg/ConfApp/UnitTest/ConfAppSetupConfUnitTest.c
- SetupDataPkg/ConfApp/UnitTest/ConfAppUnitTestCommon.c
- SetupDataPkg/Test/Include/Good_Config_Data.h
Currently, mu_feature_config is in a transition to an XML based backend. The current YAML based ConfApp expects SVDs with the IDs `"Device.ConfigData.*"`. However, the XML has no such restriction. In the case of the XML, we want to allow arbitrary SVD provided variables to be set, as this option is only provided in the manufacturing mode state (used often for bringup and debug).
This change leaves the YAML processing in place until more XML pieces are set to remove the remaining YAML pieces.
Tested with unit tests and in QemuQ35 by booting to the ConfApp in manufacturing mode, applying an SVD with arbitrary variables, rebooting to the EFI shell, using dmpstore to dump …
> Allow arbitrary SVD values to be set through ConfApp

- SetupDataPkg/SetupDataPkg.ci.yaml
- SetupDataPkg/Tools/WindowBinToNvram.py
- SetupDataPkg/Tools/WriteConfVarListToUefiVars.py
The output from ConfigUtility's  "Save Full Config Data to binary" creates binaries in UefiShell dmpstore format.
They can be directly consumed by the uefi shell.
This script allows the ability to set the information into NVRAM from windows.
Script was run from windows and data binary was written into the system's NVRAM.
`C:\Windows\System32>py -3 C:\Code\mu_feature_config\SetupDataPkg\Tools\WindowBinToNvram.py -l c:\Code\MySettings1.bin
INFO:root:Calling SetFirmwareEnvironmentVariableEx( name='Device.ConfigData.TagID_00000010 ', GUID='{7664559f-829e-48e8-a473-f12adad1ddd2}', length=0x1, attributes=0x3 )..
INFO:root:Calling SetFirmwareEnvironmentVariableEx( name='Device.ConfigData.TagID_00000020 ', GUID='{7664559f-829e-48e8-a473-f12adad1ddd2}', length=0x5D, attributes=0x3 ).. …
> Added python script to write dumpstore bin to variables from windows

- SetupDataPkg/ConfApp/ConfApp.h
- SetupDataPkg/ConfApp/SetupConf.c
- SetupDataPkg/ConfApp/UnitTest/ConfAppSetupConfUnitTest.c
Updating configuration from network will not be supported shortly. Remove this
option to clean up the page and avoid confusion.
This change is tested on QEMU virtual platform.
N/A. Removed unused and unimplemented feature option.
> Remove update configuration from network packet option

- SetupDataPkg/Docs/ConfigurationFiles/ConfigurationFiles.md
- SetupDataPkg/Tools/ConfigEditor.py
Loading CSV files was brittle, depending on the CSV filename being the same as the XML filename. This change allows the CSV filename to be loaded if the XML filename is a prefix of the CSV filename. The docs are updated with examples.
This will be updated to allow any CSV filename when the GUID is added to the CSV output and loading knobs will instead look for the unique GUID/knob name combination.
_(you can also check items in the …
> Fix CSV Loading

- SetupDataPkg/ConfApp/SetupConf.c
- pip-requirements.txt
The existing code path passed in the incorrect data length using the size of UEFI variable raw data length. This change updated it to use the full base64 encoded xml string to display to the serial port.
Another issue is that the name size variable is not updated until a larger one hits, which makes the code copied extra garbage bytes to the end data.
Tested on Qemu Q35 virtual platform …
> Fixing dump option from ConfApp

- SetupDataPkg/Tools/ConfigEditor.py
- breaking_changes.md
Standardize the binary suffix output by ConfigEditor to .vl to be in line with other tools and
dmpstore. This reflects the variable list format being used by the binary output as opposed to the generic .bin suffix.
Tested manually with the ConfigEditor loading different binary files.
To integrate this change, either manually change the suffix of existing binary files to .vl or make
the …
> Change Binary Suffix to .vl

- SetupDataPkg/Tools/KnobService.py
This fixes bug [107](https://github.com/microsoft/mu_feature_config/issues/107). Simple whitespace fix, no code functionality change. The example in the bug now prints:
```
#ifdef CONFIG_SET_VARIABLES
// Set the current value of the example knob
bool config_set_example(bool value) {
return set_knob_value(KNOB_example, &value);
}
```
- **Functionality** - Does the change ultimately impact how …
> Add Newline to KnobService.py Output

- SetupDataPkg/SetupDataPkg.ci.yaml
- SetupDataPkg/SetupDataPkg.dsc
Add libraries needed to support /GS MSVC flag.
- Examples: Unit tests, integration tests, robot tests, ...
- **Documentation** - Does the …
> SetupDataPkg.dsc: Add stack cookie support libs

- SetupDataPkg/Tools/KnobService.py
Fix a misformatted string in KnobService.py (generate_profiles) where a
stray comma makes Python misinterpret the `+` sign as a unary arithmetic
operation on a string. KnobService.py ends up crashing with  the
following exception:
`TypeError: bad operand type for unary +: 'str'`
Also add a missing UEFI type conversion for the knob being overridden.
- **Functionality** - Does the change …
> Fix a TypeError when generating knob profiles

- SetupDataPkg/Include/ConfigStdStructDefs.h
This change was missed on the PR integrating this header file. Make these values UINT32 to match the sizes expected in binary format and in consumers of this header.
- **Security** - Does the change have a direct security impact on an …
> Change to UINT32 fields

- SetupDataPkg/Tools/KnobService.py
There is currently a bug in KnobService.py where standalone enum knobs are not printed correctly in the validation functions, as it is only expecting enums inside of structs. This PR fixes that logic so builds are not broken with standalone enum knobs.
- Examples: Add a new library, publish a new PPI, update an …
> Correctly Print Validation Function for Standalone Enums in KnobService.py

- SetupDataPkg/Tools/GenNCCfgData.py
- SetupDataPkg/Tools/GenNCCfgData_test.py
A recent change in the configuration class start to require xml to be supplied from the initialization routine, which stops the command line option from generating binaries with given xml file path.
This change fixed the missing input error.
- Examples: Add a new library, publish a new PPI, update an algorithm, …
> Fixing GenBin command line option

- SetupDataPkg/Tools/ReadUefiVarsToConfVarList.py
- SetupDataPkg/Tools/SettingSupport/UefiVariablesSupportLib.py
This change added an error handling for `GetFirmwareEnvironmentVariable`, where the returned UEFI variable buffer will only be None when the buffer allocation failed.
It also removed the printouts when the OS API returned `EFI_NOT_FOUND`, because it would happen as a normal use case.
- Examples: Add a new library, …
> Do not return None when `efi_var` is allocated properly

- SetupDataPkg/Include/Library/PlatformConfigDataLib.h
- SetupDataPkg/Library/PlatformConfigDataLibNull/PlatformConfigDataLibNull.c
- SetupDataPkg/Tools/KnobService.py
This change fixes a bug from previous autogen contract data library, where the profile name field should actually be an array of `CHAR8*`.
- …
> The profile name variable should be a string array

- SetupDataPkg/SetupDataPkg.ci.yaml
Adds a PrEval entry to each ci.yaml file, which is used to enable the new PrEval policy 5.
- Examples: Unit tests, integration tests, robot …
> ci.yaml: add PrEval entry

- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/ConfigKnobShimMmLib.c
- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/ConfigKnobShimMmLib.inf
- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/UnitTest/ConfigKnobShimMmLibUnitTest.inf
- SetupDataPkg/SetupDataPkg.dsc
- SetupDataPkg/Test/SetupDataPkgHostTest.dsc
Add support for DXE_SMM_DRIVER to ConfigKnobShimMmLib, which is also renamed from ConfigKnobShimStandaloneMmLib to reflect the additional support. This is a breaking change due to the name change. Resolves #215.
- **Security** - Does the …
> Move ConfigKnobShimStandaloneMmLib to ConfigKnobShimMmLib

- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/ConfigKnobShimMmLib.inf
ConfigKnobShimMmLib is not a BASE lib and instead should be listed as MM_STANDALONE to reflect the primary library class it is.
- Examples: …
> Move ConfigKnobShimMmLib to MM_STANDALONE module type

- SetupDataPkg/Plugins/UpdateConfigHdr/UpdateConfigHdr.py
Replaces calls to `thebuilder.mws.join` to
`thebuilder.edk2path.GetAbsolutePathOnThisSystemFromEdk2RelativePath`.
- Examples: Unit tests, …
> UpdateConfigHdr.py: Resolve mws deprecation

- SetupDataPkg/Docs/PlatformIntegration/PlatformIntegrationSteps.md
- SetupDataPkg/Tools/KnobService.py
This change adds a set of getter functions that accepts a caller designated buffer for cached configuration policy. This will avoid the direct usage of updating global variable does not work (i.e. the module is XIP).
Fixes https://github.com/microsoft/mu_feature_config/issues/243.
- Examples: Add a new library, …
> Updated auto-gen script to accept cache for policy values

- .pytool/CISettings.py
Updates Mu dependencies to the latest release branch (`202302`).
- Examples: Unit tests, integration tests, robot tests, ...
- …
> .pytool/CISettings.py: Update from 202208 to 202302

- SetupDataPkg/Tools/KnobService.py
- Makes CachedPolicy type consistent in generated file.
- Removes unused CachedPolicyInitialize variable.
- Examples: Unit tests, …
> SetupDataPkg: Fix GCC failure in KnobService.py

- SetupDataPkg/Tools/KnobService.py
When the KnobService.py generate the ConfigDataGenerated.h, it generated the ValidateEnumValueXXXX function that has a switch implementation, but it missed the default: in the switch implementation that cause gcc build failed with [-Werror=switch] error.
a function …
> Add the default in switch implementation to prevent gcc build error

- SetupDataPkg/SetupDataPkg.dsc
An instance of StackCheckLib must be in each DSC to accommodate -fstack-protector and /GS flags.
- Examples: Unit tests, integration tests, …
> Add StackCheckLib Instances to Platform DSC Files

- SetupDataPkg/ConfApp/SetupConf.c
When building with CLANG/CLANGPDB, the compiler will generate errors for where the variable could be used without being initialized.
This change is added to mitigate such errors and pave way to build ARM platforms on Windows system.
- …
> Fix CLANG build errors

- .cspell.json
- SetupDataPkg/SetupDataPkg.ci.yaml
- SetupDataPkg/Tools/GenNCCfgData.py
- SetupDataPkg/Tools/GenNCCfgData_test.py
- SetupDataPkg/Tools/VariableList.py
- SetupDataPkg/Tools/configschema.xsd
- SetupDataPkg/Tools/sampleschema.xml
Add a pretty name field to the XML knobs to allow an easier time to read the configuration knobs per feature request #350 .
a function in a new …
> Add Pretty Name to Config XML

- .cspell.json
- SetupDataPkg/SetupDataPkg.ci.yaml
- SetupDataPkg/Tools/ReadUefiVarsToConfVarList.py
- SetupDataPkg/Tools/SettingSupport/UefiVariablesSupportLib.py
- SetupDataPkg/Tools/SettingSupport/UefiVariablesSupportLinuxLib.py
- SetupDataPkg/Tools/WriteConfVarListToUefiVars.py
This adds a Python script to write UEFI variables to and from config bins from Linux. The current support is only for Windows.
a function in a …
> Add Linux Variable Writing Script

- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimDxeLib/GoogleTest/ConfigKnobShimDxeLibGoogleTest.inf
- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimDxeLib/UnitTest/ConfigKnobShimDxeLibUnitTest.inf
- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/ConfigKnobShimMmLib.inf
- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimMmLib/UnitTest/ConfigKnobShimMmLibUnitTest.inf
- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimPeiLib/ConfigKnobShimPeiLib.inf
- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimPeiLib/UnitTest/ConfigKnobShimPeiLibUnitTest.inf
- SetupDataPkg/Library/ConfigKnobShimLib/UnitTest/ConfigKnobShimLibUnitTestCommon.c
Unit tests started failing due to compilation errors. This stemmed from a bug fixed in https://github.com/microsoft/mu_basecore/pull/891. Once this bug was fixed,
the unit tests starting to be compiled which blocked pipelines. 
Checking previous pipelines, these tests were not compiled due to the above mentioned bug.
Once the fix was cherry picked back into basecore 202302, it started blocking the pipelines. 
- …
> SetupDataPkg/ConfigKnobShimLib: Correct unit test compilation errors.

- .pytool/CISettings.py
Project is still floating on latest 202302 versions of mu_basecore, mu_plus and mu_tiano_plus. 
Switch to using 202311 for all submodules. 
a …
> Switch to using 202311 branchs of required repos instead of 202302

- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimPeiLib/ConfigKnobShimPeiLib.inf
- SetupDataPkg/Library/ConfigKnobShimLib/ConfigKnobShimPeiLib/GoogleTest/ConfigKnobShimPeiLibGoogleTest.inf
Commit #369 erroneously removed the implementation for GetConfigKnobOverride from ConfigKnobShimPeiLib. Adding back the implementation to PEI and fixing the unit test to correctly work, in the same fashion as Dxe/MM versions.
in build or boot …
> SetupDataPkg/ConfigKnobShimPeiLib: Revert ConfigKnobShimPeiLib change and fix unit test.

- SetupDataPkg/Plugins/UpdateConfigHdr/UpdateConfigHdr.py
`GetAbsolutePathOnThisSystemFromEdk2RelativePath` will log an error message and return `None` if absolute path could not be determined. Due to this, file should be checked against `None`, not `os.path.isfile`.
You can see that in the [GetAbsolutePathOnThisSystemFromEdk2RelativePath](https://github.com/tianocore/edk2-pytool-library/blob/b4746ac9386de524a67c2d367bba1cba45d41b61/edk2toollib/uefi/edk2/path_utilities.py#L211) that we return a str if the absolute path is found, else `None`.
Currently, when a path is not found, you get this exception and trace: …
> UpdateConfigHdr: Gracefully exit when filepath is `None`

- SetupDataPkg/ConfApp/SetupConf.c
The DEBUG message will throughout expectations, due to pass wrong type variable.  
The %g parameter need to pass the GUID pointer not the variable itself. so chang TargetGuids[i] to &TargetGuids[i]
Test have been run on an Arm based simulator. No exception throughout after adding the &. 
N/A
> SetupDataPkg/ConfApp: Fix incorrect type used in a GUID print

- .cspell.json
- SetupDataPkg/Tools/BoardMiscInfo.py
- SetupDataPkg/Tools/ConfigEditor.py
- SetupDataPkg/Tools/ReadUefiVarsToConfVarList.py
- SetupDataPkg/Tools/WriteConfVarListToUefiVars.py
In this PR, we added the below new features in config editor
1. UI menu to read/write variable from SUT in runtime
2. UI menu to delete variable listed in platformcfg.xml on SUT in runtime
3. UI to show, admin mode,  manufacturing mode and mfci policy on the lower right side
4. Status box show log output from config editor so that user can know what vl or xml file is loaded
For details on how to complete these options and their meaning refer to [CONTRIBUTING.md](https://github.com/microsoft/mu/blob/HEAD/CONTRIBUTING.md).
We tested on real SUT and verify each function we added. 
<_Describe the test(s) that were run to verify the changes._>
<_Describe how these changes should be integrated. Use N/A if nothing is required._>
N/A
> Add new features in config editor

- SetupDataPkg/Tools/WriteConfVarListToUefiVars.py
There is an unnecessary argument -x in the `WriteConfVarListToUefiVars.py` script in PR #413
For details on how to complete these options and their meaning refer to [CONTRIBUTING.md](https://github.com/microsoft/mu/blob/HEAD/CONTRIBUTING.md).
python WriteConfVarListToUefiVars.py -l test.vl and it doesn't require -x arg
N/A
> Remove xml_file args from WriteConfVarListToUefiVars.py

- SetupDataPkg/Library/PlatformConfigDataLibNull/PlatformConfigDataLibNull.c
Add missing gSchemaXmlHash in PlatformConfigDataLibNull.c for stuart_ci_build test
For details on how to complete these options and their meaning refer to [CONTRIBUTING.md](https://github.com/microsoft/mu/blob/HEAD/CONTRIBUTING.md).
stuart_ci_build pipeline test pass
> Add missing gSchemaXmlHash in PlatformConfigDataLibNull.c

- SetupDataPkg/ConfApp/BootOptions.c
The ESC behavior is not correct in ConfigApp.
Boot to ConfigApp and observe ESC help string.
N/A
> Correct the ESC behavior in ConfigApp

- SetupDataPkg/Tools/VariableList.py
Use <I instead of <i for EnumFormat in order to support UINT32 enum
Execute ConfigEditor.py and loads a config xml file with UINT32 enum values.
A sample xml has been attached in https://github.com/microsoft/mu_feature_config/issues/438
N/A
> ConfigEditor: Large Enum Value Support (#438)

- SetupDataPkg/Tools/ConfigEditor.py
If users modify some values in combo boxes without clicking the left tree and then click the pagination control buttons, the modified values may not take effect. We may need to ensure that the changes take effect in the config data before leaving the page, just like many other buttons do.
1. Execute ConfigEditor.py.
2. Load a Config XML containing a struct with more than 500 members, so the pagination control buttons appear on the right grid.
3. Modify combo box values and dropdown list selections.
4. Navigate back and forth using the pagination control to verify whether the modified values persist.
N/A
> [ConfigEditor] Update config data before leaving the page

- .azurepipelines/Ubuntu-GCC5.yml
Remove ARM as a target for CI runs.
Only target AARCH64, IA32, X64 for GCC CI.
Local CI builds. 
Not Applicable since it is a CI change.
> CI: Limit CI runs to AARCH64, IA32, X64.

- .cspell.json
- SetupDataPkg/Tools/GenNCCfgData.py
The current config editor tool requires UI interface to modify config variables.
Although, we can use multiple GenNCCfgData.py cmd lines/config.xml tweak to achieve same functions, but it's not convenient to use 
This PR adds a ModConfig.py cmd line interface to modify config variables.
Usage:
$ python GenNCCfgData.py MODCONFIG --xml_file config.xml --var knob1 --var knob2 --val knob_val1 --val knob_val2 [--output_file out.vl]
modify <array>int config var
$ python GenNCCfgData.py MODCONFIG --xml_file config.xml --var "NetworkBootOrder" --val "[1,3,2,4]"
Delete all config var
$ python GenNCCfgData.py DELVAR --xml_file config.xml
Tested on SUT and make sure the config variables can be modified or deleted
Old function GENBIN and GENCSV are also working like before.
N/A
> Add MODCONFIG/DELVAR cmd line interface to modify config variables

- SetupDataPkg/Tools/KnobService.py
In the autogen service header (e.g. ConfigServiceGenerated.h), PcdGetPtr() and CopyMem() are invoked, but it does not include corresponding PcdLib.h and BaseMemoryLib.h.
Currently when we include ConfigServiceGenerated.h in another .c file, we usually get build errors and realize that we also need to include PcdLib.h and BaseMemoryLib.h.
It would be better if we could have the right inclusion in the autogen header, as well as ConfigClientGenerated.h includes Uefi.h.
For details on how to complete these options and their meaning refer to [CONTRIBUTING.md](https://github.com/microsoft/mu/blob/HEAD/CONTRIBUTING.md).
- Built and Booted System UEFI with .c files which include ConfigServiceGenerated.h.
- Built and Booted System UEFI with .c filfes which include ConfigServiceGenerated.h and also …
> Include PcdLib and BaseMemoryLib since in the autogen header since it invokes PcdGetPtr() and CopyMem()

- SetupDataPkg/ConfApp/ConfApp.c
When compiling with clangdwarf, a build error is throw because a UINT32 variable is being compared against a MAX_UINTN.
This works fine for IA32 builds, but fails for x64.
Compiling with clangdwarf, encountered an error. After fix, compilation is successful.
No integration necessary.
> SetupDataPkg: ConfApp fix size comparison mismatch.
